name: Format & Lint
on:
  push:
  pull_request:

jobs:
  format-lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Install tools
        run: make install-tools

      - name: Format
        run: make fmt

      - name: Lint
        run: make lint
